#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             12
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
# spacebar -m config text_font          "FantasqueSansMono Nerd Font:Bold:12.0"
# spacebar -m config text_font          "SpaceMono Nerd Font:Bold:11.0"
# spacebar -m config text_font          "GohuFont uni11 Nerd Font:Regular:11.0"
# spacebar -m config icon_font          "GohuFont uni11 Nerd Font:Regular:11.0"
# spacebar -m config icon_font          "Font Awesome 5 Free:Regular:12.0"
spacebar -m config icon_font          "FantasqueSansMono Nerd Font:Bold:11.0"
spacebar -m config icon_font          "FantasqueSansMono Nerd Font:Bold:11.0"
spacebar -m config background_color   0xff181616
spacebar -m config foreground_color   0xffc5c9c5
spacebar -m config space_icon_color   0xff8ba4b0
spacebar -m config power_icon_color   0xff8a9a7b
spacebar -m config battery_icon_color 0xffc4746e
spacebar -m config dnd_icon_color     0xffa292a3
spacebar -m config clock_icon_color   0xffc4b28a
spacebar -m config space_icon_strip   [one] [two] [three] [four] [five] [six]
# spacebar -m config space_icon_strip   one two three four five six
# spacebar -m config display_separator on
# spacebar -m config display_separator_icon |
spacebar -m config dnd off
spacebar -m config power_icon_strip   󰁾 󰂄
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%a %m/%d  %I:%M %p"

# Music
spacebar -m config title on
# spacebar -m config right_shell                 on
# spacebar -m config right_shell_icon            
# spacebar -m config right_shell_command         "whoami"
spacebar -m config center_shell off
# spacebar -m config center_shell_command "bash ~/.config/cmus/spacebar.sh"

echo "spacebar configuration loaded.."
