#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             20
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
# spacebar -m config text_font          "FantasqueSansMono Nerd Font:Bold:12.0"
spacebar -m config text_font          "FantasqueSansMono Nerd Font:Bold:12.0"
# spacebar -m config icon_font          "Font Awesome 5 Free:Regular:12.0"
# spacebar -m config icon_font          "FantasqueSansMono Nerd Font:Bold:12.0"
spacebar -m config icon_font          "FantasqueSansMono Nerd Font:Bold:12.0"
spacebar -m config background_color   0xff575268
spacebar -m config foreground_color   0xffC9CBFF
spacebar -m config space_icon_color   0xffF5C2E7
spacebar -m config power_icon_color   0xffABE9B3
spacebar -m config battery_icon_color 0xffF8BD96
spacebar -m config dnd_icon_color     0xffC9CBFF
spacebar -m config clock_icon_color   0xff89DCEB
spacebar -m config space_icon_strip   one two three four five six
# spacebar -m config space_icon_strip   one two three four five six
# spacebar -m config display_separator on
# spacebar -m config display_separator_icon |
spacebar -m config dnd on
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%a %m/%d  %I:%M %p"

# Music
spacebar -m config title off
# spacebar -m config right_shell                 on
# spacebar -m config right_shell_icon            
# spacebar -m config right_shell_command         "whoami"
spacebar -m config center_shell on
spacebar -m config center_shell_command "bash ~/.config/cmus/spacebar.sh"

echo "spacebar configuration loaded.."
